// go run vk_gen.go
// Code generated by the command above; DO NOT EDIT.

package vxr

import "slices"

func getExtensionDependencies(name string) []string {
	switch (name) {
	case "VK_AMD_display_native_hdr":
		return []string{"VK_KHR_swapchain"}
	case "VK_AMD_shader_core_properties2":
		return []string{"VK_AMD_shader_core_properties"}
	case "VK_ANDROID_external_format_resolve":
		return []string{"VK_ANDROID_external_memory_android_hardware_buffer"}
	case "VK_ANDROID_external_memory_android_hardware_buffer":
		return []string{"VK_KHR_sampler_ycbcr_conversion", "VK_KHR_external_memory", "VK_KHR_dedicated_allocation", "VK_EXT_queue_family_foreign"}
	case "VK_ARM_data_graph":
		return []string{"VK_KHR_maintenance5", "VK_KHR_deferred_host_operations"}
	case "VK_ARM_pipeline_opacity_micromap":
		return []string{"VK_EXT_opacity_micromap"}
	case "VK_ARM_render_pass_striped":
		return []string{"VK_KHR_synchronization2"}
	case "VK_ARM_scheduling_controls":
		return []string{"VK_ARM_shader_core_builtins"}
	case "VK_EXT_attachment_feedback_loop_dynamic_state":
		return []string{"VK_EXT_attachment_feedback_loop_layout"}
	case "VK_EXT_border_color_swizzle":
		return []string{"VK_EXT_custom_border_color"}
	case "VK_EXT_descriptor_buffer":
		return []string{"VK_KHR_buffer_device_address", "VK_EXT_descriptor_indexing", "VK_KHR_synchronization2"}
	case "VK_EXT_descriptor_indexing":
		return []string{"VK_KHR_maintenance3"}
	case "VK_EXT_device_generated_commands":
		return []string{"VK_KHR_buffer_device_address", "VK_KHR_maintenance5"}
	case "VK_EXT_display_control":
		return []string{"VK_KHR_swapchain"}
	case "VK_EXT_dynamic_rendering_unused_attachments":
		return []string{"VK_KHR_dynamic_rendering"}
	case "VK_EXT_external_memory_acquire_unmodified":
		return []string{"VK_KHR_external_memory"}
	case "VK_EXT_external_memory_dma_buf":
		return []string{"VK_KHR_external_memory_fd"}
	case "VK_EXT_external_memory_host":
		return []string{"VK_KHR_external_memory"}
	case "VK_EXT_external_memory_metal":
		return []string{"VK_KHR_external_memory"}
	case "VK_EXT_fragment_density_map2":
		return []string{"VK_EXT_fragment_density_map"}
	case "VK_EXT_fragment_density_map_offset":
		return []string{"VK_EXT_fragment_density_map", "VK_KHR_create_renderpass2", "VK_KHR_dynamic_rendering"}
	case "VK_EXT_full_screen_exclusive":
		return []string{"VK_KHR_swapchain"}
	case "VK_EXT_global_priority_query":
		return []string{"VK_EXT_global_priority"}
	case "VK_EXT_graphics_pipeline_library":
		return []string{"VK_KHR_pipeline_library"}
	case "VK_EXT_hdr_metadata":
		return []string{"VK_KHR_swapchain"}
	case "VK_EXT_host_image_copy":
		return []string{"VK_KHR_copy_commands2", "VK_KHR_format_feature_flags2"}
	case "VK_EXT_image_2d_view_of_3d":
		return []string{"VK_KHR_maintenance1"}
	case "VK_EXT_image_compression_control_swapchain":
		return []string{"VK_EXT_image_compression_control"}
	case "VK_EXT_image_drm_format_modifier":
		return []string{"VK_KHR_bind_memory2", "VK_KHR_sampler_ycbcr_conversion", "VK_KHR_image_format_list"}
	case "VK_EXT_image_sliced_view_of_3d":
		return []string{"VK_KHR_maintenance1"}
	case "VK_EXT_inline_uniform_block":
		return []string{"VK_KHR_maintenance1"}
	case "VK_EXT_legacy_vertex_attributes":
		return []string{"VK_EXT_vertex_input_dynamic_state"}
	case "VK_EXT_map_memory_placed":
		return []string{"VK_KHR_map_memory2"}
	case "VK_EXT_mesh_shader":
		return []string{"VK_KHR_spirv_1_4"}
	case "VK_EXT_multisampled_render_to_single_sampled":
		return []string{"VK_KHR_create_renderpass2", "VK_KHR_depth_stencil_resolve"}
	case "VK_EXT_mutable_descriptor_type":
		return []string{"VK_KHR_maintenance3"}
	case "VK_EXT_opacity_micromap":
		return []string{"VK_KHR_acceleration_structure", "VK_KHR_synchronization2"}
	case "VK_EXT_pageable_device_local_memory":
		return []string{"VK_EXT_memory_priority"}
	case "VK_EXT_pipeline_library_group_handles":
		return []string{"VK_KHR_ray_tracing_pipeline", "VK_KHR_pipeline_library"}
	case "VK_EXT_present_mode_fifo_latest_ready":
		return []string{"VK_KHR_swapchain"}
	case "VK_EXT_primitives_generated_query":
		return []string{"VK_EXT_transform_feedback"}
	case "VK_EXT_queue_family_foreign":
		return []string{"VK_KHR_external_memory"}
	case "VK_EXT_rgba10x6_formats":
		return []string{"VK_KHR_sampler_ycbcr_conversion"}
	case "VK_EXT_shader_atomic_float2":
		return []string{"VK_EXT_shader_atomic_float"}
	case "VK_EXT_shader_module_identifier":
		return []string{"VK_EXT_pipeline_creation_cache_control"}
	case "VK_EXT_shader_object":
		return []string{"VK_KHR_dynamic_rendering"}
	case "VK_EXT_swapchain_maintenance1":
		return []string{"VK_KHR_swapchain"}
	case "VK_EXT_ycbcr_2plane_444_formats":
		return []string{"VK_KHR_sampler_ycbcr_conversion"}
	case "VK_EXT_ycbcr_image_arrays":
		return []string{"VK_KHR_sampler_ycbcr_conversion"}
	case "VK_FUCHSIA_buffer_collection":
		return []string{"VK_FUCHSIA_external_memory", "VK_KHR_sampler_ycbcr_conversion"}
	case "VK_FUCHSIA_external_memory":
		return []string{"VK_KHR_external_memory"}
	case "VK_FUCHSIA_external_semaphore":
		return []string{"VK_KHR_external_semaphore"}
	case "VK_GGP_frame_token":
		return []string{"VK_KHR_swapchain"}
	case "VK_GOOGLE_display_timing":
		return []string{"VK_KHR_swapchain"}
	case "VK_HUAWEI_hdr_vivid":
		return []string{"VK_KHR_swapchain", "VK_EXT_hdr_metadata"}
	case "VK_HUAWEI_invocation_mask":
		return []string{"VK_KHR_ray_tracing_pipeline", "VK_KHR_synchronization2"}
	case "VK_HUAWEI_subpass_shading":
		return []string{"VK_KHR_create_renderpass2", "VK_KHR_synchronization2"}
	case "VK_KHR_16bit_storage":
		return []string{"VK_KHR_storage_buffer_storage_class"}
	case "VK_KHR_8bit_storage":
		return []string{"VK_KHR_storage_buffer_storage_class"}
	case "VK_KHR_acceleration_structure":
		return []string{"VK_EXT_descriptor_indexing", "VK_KHR_buffer_device_address", "VK_KHR_deferred_host_operations"}
	case "VK_KHR_buffer_device_address":
		return []string{"VK_KHR_device_group"}
	case "VK_KHR_copy_memory_indirect":
		return []string{"VK_KHR_buffer_device_address"}
	case "VK_KHR_create_renderpass2":
		return []string{"VK_KHR_multiview", "VK_KHR_maintenance2"}
	case "VK_KHR_dedicated_allocation":
		return []string{"VK_KHR_get_memory_requirements2"}
	case "VK_KHR_depth_stencil_resolve":
		return []string{"VK_KHR_create_renderpass2"}
	case "VK_KHR_display_swapchain":
		return []string{"VK_KHR_swapchain"}
	case "VK_KHR_dynamic_rendering":
		return []string{"VK_KHR_depth_stencil_resolve"}
	case "VK_KHR_dynamic_rendering_local_read":
		return []string{"VK_KHR_dynamic_rendering"}
	case "VK_KHR_external_fence_fd":
		return []string{"VK_KHR_external_fence"}
	case "VK_KHR_external_fence_win32":
		return []string{"VK_KHR_external_fence"}
	case "VK_KHR_external_memory_fd":
		return []string{"VK_KHR_external_memory"}
	case "VK_KHR_external_memory_win32":
		return []string{"VK_KHR_external_memory"}
	case "VK_KHR_external_semaphore_fd":
		return []string{"VK_KHR_external_semaphore"}
	case "VK_KHR_external_semaphore_win32":
		return []string{"VK_KHR_external_semaphore"}
	case "VK_KHR_fragment_shading_rate":
		return []string{"VK_KHR_create_renderpass2"}
	case "VK_KHR_imageless_framebuffer":
		return []string{"VK_KHR_maintenance2", "VK_KHR_image_format_list"}
	case "VK_KHR_incremental_present":
		return []string{"VK_KHR_swapchain"}
	case "VK_KHR_maintenance5":
		return []string{"VK_KHR_dynamic_rendering"}
	case "VK_KHR_pipeline_binary":
		return []string{"VK_KHR_maintenance5"}
	case "VK_KHR_present_id":
		return []string{"VK_KHR_swapchain"}
	case "VK_KHR_present_id2":
		return []string{"VK_KHR_swapchain"}
	case "VK_KHR_present_mode_fifo_latest_ready":
		return []string{"VK_KHR_swapchain"}
	case "VK_KHR_present_wait":
		return []string{"VK_KHR_swapchain", "VK_KHR_present_id"}
	case "VK_KHR_present_wait2":
		return []string{"VK_KHR_swapchain", "VK_KHR_present_id2"}
	case "VK_KHR_ray_query":
		return []string{"VK_KHR_spirv_1_4", "VK_KHR_acceleration_structure"}
	case "VK_KHR_ray_tracing_maintenance1":
		return []string{"VK_KHR_acceleration_structure"}
	case "VK_KHR_ray_tracing_pipeline":
		return []string{"VK_KHR_spirv_1_4", "VK_KHR_acceleration_structure"}
	case "VK_KHR_ray_tracing_position_fetch":
		return []string{"VK_KHR_acceleration_structure"}
	case "VK_KHR_sampler_ycbcr_conversion":
		return []string{"VK_KHR_maintenance1", "VK_KHR_bind_memory2", "VK_KHR_get_memory_requirements2"}
	case "VK_KHR_separate_depth_stencil_layouts":
		return []string{"VK_KHR_create_renderpass2"}
	case "VK_KHR_shader_float_controls2":
		return []string{"VK_KHR_shader_float_controls"}
	case "VK_KHR_shader_quad_control":
		return []string{"VK_KHR_vulkan_memory_model", "VK_KHR_shader_maximal_reconvergence"}
	case "VK_KHR_shared_presentable_image":
		return []string{"VK_KHR_swapchain"}
	case "VK_KHR_spirv_1_4":
		return []string{"VK_KHR_shader_float_controls"}
	case "VK_KHR_swapchain_maintenance1":
		return []string{"VK_KHR_swapchain"}
	case "VK_KHR_swapchain_mutable_format":
		return []string{"VK_KHR_swapchain", "VK_KHR_maintenance2", "VK_KHR_image_format_list"}
	case "VK_KHR_variable_pointers":
		return []string{"VK_KHR_storage_buffer_storage_class"}
	case "VK_KHR_video_decode_av1":
		return []string{"VK_KHR_video_decode_queue"}
	case "VK_KHR_video_decode_h264":
		return []string{"VK_KHR_video_decode_queue"}
	case "VK_KHR_video_decode_h265":
		return []string{"VK_KHR_video_decode_queue"}
	case "VK_KHR_video_decode_queue":
		return []string{"VK_KHR_video_queue", "VK_KHR_synchronization2"}
	case "VK_KHR_video_decode_vp9":
		return []string{"VK_KHR_video_decode_queue"}
	case "VK_KHR_video_encode_av1":
		return []string{"VK_KHR_video_encode_queue"}
	case "VK_KHR_video_encode_h264":
		return []string{"VK_KHR_video_encode_queue"}
	case "VK_KHR_video_encode_h265":
		return []string{"VK_KHR_video_encode_queue"}
	case "VK_KHR_video_encode_intra_refresh":
		return []string{"VK_KHR_video_encode_queue"}
	case "VK_KHR_video_encode_quantization_map":
		return []string{"VK_KHR_video_encode_queue", "VK_KHR_format_feature_flags2"}
	case "VK_KHR_video_encode_queue":
		return []string{"VK_KHR_video_queue", "VK_KHR_synchronization2"}
	case "VK_KHR_video_maintenance1":
		return []string{"VK_KHR_video_queue"}
	case "VK_KHR_video_maintenance2":
		return []string{"VK_KHR_video_queue"}
	case "VK_KHR_video_queue":
		return []string{"VK_KHR_synchronization2"}
	case "VK_KHR_win32_keyed_mutex":
		return []string{"VK_KHR_external_memory_win32"}
	case "VK_NVX_multiview_per_view_attributes":
		return []string{"VK_KHR_multiview"}
	case "VK_NV_cluster_acceleration_structure":
		return []string{"VK_KHR_acceleration_structure"}
	case "VK_NV_cooperative_matrix2":
		return []string{"VK_KHR_cooperative_matrix"}
	case "VK_NV_copy_memory_indirect":
		return []string{"VK_KHR_buffer_device_address"}
	case "VK_NV_coverage_reduction_mode":
		return []string{"VK_NV_framebuffer_mixed_samples"}
	case "VK_NV_dedicated_allocation_image_aliasing":
		return []string{"VK_KHR_dedicated_allocation"}
	case "VK_NV_device_generated_commands":
		return []string{"VK_KHR_buffer_device_address"}
	case "VK_NV_device_generated_commands_compute":
		return []string{"VK_NV_device_generated_commands"}
	case "VK_NV_external_memory_rdma":
		return []string{"VK_KHR_external_memory"}
	case "VK_NV_external_memory_win32":
		return []string{"VK_NV_external_memory"}
	case "VK_NV_fragment_shading_rate_enums":
		return []string{"VK_KHR_fragment_shading_rate"}
	case "VK_NV_low_latency2":
		return []string{"VK_KHR_timeline_semaphore", "VK_KHR_present_id", "VK_KHR_present_id2"}
	case "VK_NV_memory_decompression":
		return []string{"VK_KHR_buffer_device_address"}
	case "VK_NV_optical_flow":
		return []string{"VK_KHR_format_feature_flags2", "VK_KHR_synchronization2"}
	case "VK_NV_partitioned_acceleration_structure":
		return []string{"VK_KHR_acceleration_structure"}
	case "VK_NV_per_stage_descriptor_set":
		return []string{"VK_KHR_maintenance6"}
	case "VK_NV_present_barrier":
		return []string{"VK_KHR_swapchain"}
	case "VK_NV_ray_tracing":
		return []string{"VK_KHR_get_memory_requirements2"}
	case "VK_NV_ray_tracing_invocation_reorder":
		return []string{"VK_KHR_ray_tracing_pipeline"}
	case "VK_NV_ray_tracing_linear_swept_spheres":
		return []string{"VK_KHR_ray_tracing_pipeline"}
	case "VK_NV_ray_tracing_motion_blur":
		return []string{"VK_KHR_ray_tracing_pipeline"}
	case "VK_NV_win32_keyed_mutex":
		return []string{"VK_NV_external_memory_win32"}
	case "VK_QCOM_filter_cubic_clamp":
		return []string{"VK_EXT_filter_cubic", "VK_EXT_sampler_filter_minmax"}
	case "VK_QCOM_filter_cubic_weights":
		return []string{"VK_EXT_filter_cubic"}
	case "VK_QCOM_fragment_density_map_offset":
		return []string{"VK_EXT_fragment_density_map"}
	case "VK_QCOM_image_processing":
		return []string{"VK_KHR_format_feature_flags2"}
	case "VK_QCOM_image_processing2":
		return []string{"VK_QCOM_image_processing"}
	case "VK_QCOM_rotated_copy_commands":
		return []string{"VK_KHR_copy_commands2"}
	case "VK_QCOM_tile_memory_heap":
		return []string{"VK_KHR_get_memory_requirements2"}
	case "VK_QCOM_tile_shading":
		return []string{"VK_QCOM_tile_properties"}
	case "VK_QNX_external_memory_screen_buffer":
		return []string{"VK_KHR_sampler_ycbcr_conversion", "VK_KHR_external_memory", "VK_KHR_dedicated_allocation", "VK_EXT_queue_family_foreign"}
	case "VK_VALVE_fragment_density_map_layered":
		return []string{"VK_KHR_maintenance5", "VK_EXT_fragment_density_map"}
	case "VK_VALVE_mutable_descriptor_type":
		return []string{"VK_KHR_maintenance3"}
	case "VK_VALVE_video_encode_rgb_conversion":
		return []string{"VK_KHR_video_encode_queue", "VK_KHR_sampler_ycbcr_conversion"}
	}
	return nil
}

func filterCorePromotedExtensions(version uint32, extensions []string) []string {
	slices.Sort(extensions)
	extensions = slices.DeleteFunc(extensions, func(e string) bool {
		switch e {
			case "VK_EXT_4444_formats":
				return version >= 4206592
			case "VK_EXT_descriptor_indexing":
				return version >= 4202496
			case "VK_EXT_extended_dynamic_state":
				return version >= 4206592
			case "VK_EXT_extended_dynamic_state2":
				return version >= 4206592
			case "VK_EXT_host_image_copy":
				return version >= 4210688
			case "VK_EXT_host_query_reset":
				return version >= 4202496
			case "VK_EXT_image_robustness":
				return version >= 4206592
			case "VK_EXT_inline_uniform_block":
				return version >= 4206592
			case "VK_EXT_pipeline_creation_cache_control":
				return version >= 4206592
			case "VK_EXT_pipeline_creation_feedback":
				return version >= 4206592
			case "VK_EXT_pipeline_protected_access":
				return version >= 4210688
			case "VK_EXT_pipeline_robustness":
				return version >= 4210688
			case "VK_EXT_private_data":
				return version >= 4206592
			case "VK_EXT_sampler_filter_minmax":
				return version >= 4202496
			case "VK_EXT_scalar_block_layout":
				return version >= 4202496
			case "VK_EXT_separate_stencil_usage":
				return version >= 4202496
			case "VK_EXT_shader_demote_to_helper_invocation":
				return version >= 4206592
			case "VK_EXT_shader_subgroup_ballot":
				return version >= 4202496
			case "VK_EXT_shader_subgroup_vote":
				return version >= 4198400
			case "VK_EXT_shader_viewport_index_layer":
				return version >= 4202496
			case "VK_EXT_subgroup_size_control":
				return version >= 4206592
			case "VK_EXT_texel_buffer_alignment":
				return version >= 4206592
			case "VK_EXT_texture_compression_astc_hdr":
				return version >= 4206592
			case "VK_EXT_tooling_info":
				return version >= 4206592
			case "VK_EXT_ycbcr_2plane_444_formats":
				return version >= 4206592
			case "VK_KHR_16bit_storage":
				return version >= 4198400
			case "VK_KHR_8bit_storage":
				return version >= 4202496
			case "VK_KHR_bind_memory2":
				return version >= 4198400
			case "VK_KHR_buffer_device_address":
				return version >= 4202496
			case "VK_KHR_copy_commands2":
				return version >= 4206592
			case "VK_KHR_create_renderpass2":
				return version >= 4202496
			case "VK_KHR_dedicated_allocation":
				return version >= 4198400
			case "VK_KHR_depth_stencil_resolve":
				return version >= 4202496
			case "VK_KHR_descriptor_update_template":
				return version >= 4198400
			case "VK_KHR_device_group":
				return version >= 4198400
			case "VK_KHR_draw_indirect_count":
				return version >= 4202496
			case "VK_KHR_driver_properties":
				return version >= 4202496
			case "VK_KHR_dynamic_rendering":
				return version >= 4206592
			case "VK_KHR_dynamic_rendering_local_read":
				return version >= 4210688
			case "VK_KHR_external_fence":
				return version >= 4198400
			case "VK_KHR_external_memory":
				return version >= 4198400
			case "VK_KHR_external_semaphore":
				return version >= 4198400
			case "VK_KHR_format_feature_flags2":
				return version >= 4206592
			case "VK_KHR_get_memory_requirements2":
				return version >= 4198400
			case "VK_KHR_global_priority":
				return version >= 4210688
			case "VK_KHR_image_format_list":
				return version >= 4202496
			case "VK_KHR_imageless_framebuffer":
				return version >= 4202496
			case "VK_KHR_index_type_uint8":
				return version >= 4210688
			case "VK_KHR_line_rasterization":
				return version >= 4210688
			case "VK_KHR_load_store_op_none":
				return version >= 4210688
			case "VK_KHR_maintenance1":
				return version >= 4198400
			case "VK_KHR_maintenance2":
				return version >= 4198400
			case "VK_KHR_maintenance3":
				return version >= 4198400
			case "VK_KHR_maintenance4":
				return version >= 4206592
			case "VK_KHR_maintenance5":
				return version >= 4210688
			case "VK_KHR_maintenance6":
				return version >= 4210688
			case "VK_KHR_map_memory2":
				return version >= 4210688
			case "VK_KHR_multiview":
				return version >= 4198400
			case "VK_KHR_push_descriptor":
				return version >= 4210688
			case "VK_KHR_relaxed_block_layout":
				return version >= 4198400
			case "VK_KHR_sampler_mirror_clamp_to_edge":
				return version >= 4202496
			case "VK_KHR_sampler_ycbcr_conversion":
				return version >= 4198400
			case "VK_KHR_separate_depth_stencil_layouts":
				return version >= 4202496
			case "VK_KHR_shader_atomic_int64":
				return version >= 4202496
			case "VK_KHR_shader_draw_parameters":
				return version >= 4198400
			case "VK_KHR_shader_expect_assume":
				return version >= 4210688
			case "VK_KHR_shader_float16_int8":
				return version >= 4202496
			case "VK_KHR_shader_float_controls":
				return version >= 4202496
			case "VK_KHR_shader_float_controls2":
				return version >= 4210688
			case "VK_KHR_shader_integer_dot_product":
				return version >= 4206592
			case "VK_KHR_shader_non_semantic_info":
				return version >= 4206592
			case "VK_KHR_shader_subgroup_extended_types":
				return version >= 4202496
			case "VK_KHR_shader_subgroup_rotate":
				return version >= 4210688
			case "VK_KHR_shader_terminate_invocation":
				return version >= 4206592
			case "VK_KHR_spirv_1_4":
				return version >= 4202496
			case "VK_KHR_storage_buffer_storage_class":
				return version >= 4198400
			case "VK_KHR_synchronization2":
				return version >= 4206592
			case "VK_KHR_timeline_semaphore":
				return version >= 4202496
			case "VK_KHR_uniform_buffer_standard_layout":
				return version >= 4202496
			case "VK_KHR_variable_pointers":
				return version >= 4198400
			case "VK_KHR_vertex_attribute_divisor":
				return version >= 4210688
			case "VK_KHR_vulkan_memory_model":
				return version >= 4202496
			case "VK_KHR_zero_initialize_workgroup_memory":
				return version >= 4206592
		}
		return false
	})
	return slices.Clip(extensions)
}
