// go run const_gen.go 
// Code generated by the command above; DO NOT EDIT.

package vxr

const(
shadercVersion = "v2025.1"
shadercSHA256 = "358f9fa87b503bc7a3efe1575fbf581fca7f16dbc6d502ea2b02628d2d0d4014"

glslangVersion = "vulkan-sdk-1.4.309"
glslangSHA256 = "d22e1fec486ab88d4877faf307594ac0f56a67c9deaf56145627516f91d56be5"

spirvHeadersVersion = "vulkan-sdk-1.4.309"
spirvHeadersSHA256 = "10f2c9136607ba1017e9da7683ff221430de7701b6521144ba56a68e99a1fa5b"

spirvToolsVersion = "vulkan-sdk-1.4.309"
spirvToolsSHA256 = "b51becb067e21b9449d27dc61f0c3c5f9dd0b9792c8f83c0e40e3bb223149e5d"

spirvCrossVersion = "vulkan-sdk-1.4.309"
spirvCrossSHA256 = "799fe961db704b87168bd42a32479de0c6953c2212d6f5a1f8b3fd9945785601"
)
