// go run const_gen.go 
// Code generated by the command above; DO NOT EDIT.

package vxr

const(
shadercVersion = "v2025.3"
shadercSHA256 = "a8e4a25e5c2686fd36981e527ed05e451fcfc226bddf350f4e76181371190937"

glslangVersion = "vulkan-sdk-1.4.321"
glslangSHA256 = "057e9dba023042b873afc4d1fade8b40664b93d203d4adab5b375c559f4b477f"

spirvHeadersVersion = "vulkan-sdk-1.4.321"
spirvHeadersSHA256 = "f8bc5f7a8259daa52010e52f87e655f3aa3176bd4ce6b44b2134ae248d355bb3"

spirvToolsVersion = "vulkan-sdk-1.4.321"
spirvToolsSHA256 = "6f797ae78a742aeeb849bd2f042550ddd9a423ceb9c44588a9fd5fe5bcf902cd"

spirvCrossVersion = "vulkan-sdk-1.4.321"
spirvCrossSHA256 = "4b4bb02effc7a58790e5c61b483065c33144f72e99c6a2707925422bb399091a"
)
