// go run const_gen.go 
// Code generated by the command above; DO NOT EDIT.

package vxr

const(
shadercVersion = "v2025.4"
shadercSHA256 = "8a89fb6612ace8954470aae004623374a8fc8b7a34a4277bee5527173b064faf"

glslangVersion = "vulkan-sdk-1.4.328"
glslangSHA256 = "87668bae71abc1a3a5fa2b534a4445fce2a244d73643e63d2eb8d8fff3ba190e"

spirvHeadersVersion = "vulkan-sdk-1.4.328"
spirvHeadersSHA256 = "6fc0fa636dfa22d89ed1c6645c0d16d6b9e3aaec34e4dab2750fac1d9bfc7329"

spirvToolsVersion = "vulkan-sdk-1.4.328"
spirvToolsSHA256 = "706b6812e800d6c8b89a15a9de79b7a9cc6036314b3474e9b3fa9efad092bc79"

spirvCrossVersion = "vulkan-sdk-1.4.328"
spirvCrossSHA256 = "6f9a5bbd35f821b3fc07d0b82032457e330f87f7704fd292a5b29da4feb688dd"
)
