//go:build ignore
// +build ignore

/*
Copyright 2025 The goARRG Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

	http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"crypto/sha256"
	"encoding/hex"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"strings"

	"goarrg.com/toolchain/cgodep"
	"goarrg.com/toolchain/golang"
	"golang.org/x/tools/go/packages"
)

func writeConst(out io.Writer, repo, constName, fileName, version string) {
	os.RemoveAll(filepath.Join(cgodep.DataDir(), "cache", fileName+".tar.gz"))
	data, err := cgodep.Get(repo+version+".tar.gz", fileName+".tar.gz", func(target io.ReadSeeker) error {
		return nil
	})
	if err != nil {
		panic(err)
	}

	h := sha256.New()
	if _, err := io.Copy(h, data); err != nil {
		panic(err)
	}
	sha256 := hex.EncodeToString(h.Sum(nil))

	fmt.Fprintf(out, "\n%sVersion = %q\n", constName, version)
	fmt.Fprintf(out, "%sSHA256 = %q\n", constName, sha256)
}

func main() {
	p := golang.CallersPackage(packages.NeedModule | packages.NeedName)
	fOut, err := os.Create(filepath.Join(p.Module.Dir, strings.TrimPrefix(p.PkgPath, p.Module.Path), "const.go"))
	if err != nil {
		panic(err)
	}

	fmt.Fprintf(fOut, "// go run const_gen.go \n")
	fmt.Fprintf(fOut, "// Code generated by the command above; DO NOT EDIT.\n\n")
	fmt.Fprintf(fOut, "package vxr\n\n")
	fmt.Fprintf(fOut, "const(")

	sdkVersion := "vulkan-sdk-1.4.313"

	writeConst(fOut, "https://github.com/google/shaderc/archive/refs/tags/", "shaderc", "shaderc", "v2025.2")
	writeConst(fOut, "https://github.com/KhronosGroup/glslang/archive/refs/heads/", "glslang", "glslang", sdkVersion)
	writeConst(fOut, "https://github.com/KhronosGroup/SPIRV-Headers/archive/refs/heads/", "spirvHeaders", "spirv-headers", sdkVersion)
	writeConst(fOut, "https://github.com/KhronosGroup/SPIRV-Tools/archive/refs/heads/", "spirvTools", "spirv-tools", sdkVersion)
	writeConst(fOut, "https://github.com/KhronosGroup/SPIRV-Cross/archive/refs/heads/", "spirvCross", "spirv-cross", sdkVersion)

	fmt.Fprintf(fOut, ")\n")
}
